# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/3_1_2bitMUX.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/Mainmenu.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/Oled_Display.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/ToPixel.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/acceleration.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/breathing.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/clk_oled.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/debouncer.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/dff.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/freezer.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/gameassets.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/gamestatus.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/improvement_mode.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/mainmenubg.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/rgb.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/signalextend.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/textmenu.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/volumebar.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/volumebar1.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/volumebar2.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/Top_Student.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/Audio_Capture.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/platformer.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/playerdraw.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/treesbg.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/PlatformerEND.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/miclevels.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/peak_generator.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/random_game_choose.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/change_digits.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/display_pass_fail.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/hello.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/led_pop.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/shout_help.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/gamer_layout.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/check_anode.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/display_random_number.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/hi_display.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/button_left_right.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/create_hint_signal.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/prompt_player2.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/runman_LR_push.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/lives_update.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/points_update.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/whacko_game.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/point_catch.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/signal_change_prog.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/display_multiple_seg.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/run_man_game.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/pass_test.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/random_number_guess.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/display_welcome.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/translate_digit.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/anode_runman.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/game_layoutB.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/game_layout_board1.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/display_lives.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/determine_hint_reveal.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/final_display.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/intensity_analysis.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/easier_time.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/change_letter_runman.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/distancetoled.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/set_decibals.v}
  {C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/sources_1/new/display_mul_random.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Abner/Desktop/Y1Sem2/EE2026 Digital Design/Proj/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
